# Generated by Django 5.2.2 on 2025-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='You',
            field=models.CharField(default=1, verbose_name='Ютуб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='infouser/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='instogram',
            field=models.URLField(default=1, verbose_name='Инстограм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='twiter',
            field=models.URLField(default=1, verbose_name='Телерам'),
            preserve_default=False,
        ),
    ]
