# Generated by Django 5.2.2 on 2025-06-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_infouser_you_infouser_description_infouser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='You',
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='instogram',
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='twiter',
        ),
    ]
