# Generated by Django 5.2.2 on 2025-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_infouser_you_infouser_description_infouser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='Happy_Clients',
            field=models.IntegerField(default=1, verbose_name='Довольные клиенты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='Project',
            field=models.IntegerField(default=1, verbose_name='Завершенный проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='Years_Experience',
            field=models.IntegerField(default=1, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
    ]
