# Generated by Django 5.2.2 on 2025-07-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_infouser_happy_clients_infouser_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infouser',
            old_name='twiter',
            new_name='telegram',
        ),
        migrations.AddField(
            model_name='infouser',
            name='Google',
            field=models.CharField(default=1, verbose_name='Гугл'),
            preserve_default=False,
        ),
    ]
