# Generated by Django 5.2.2 on 2025-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_twiter_infouser_telegram_infouser_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='instogram',
        ),
        migrations.AddField(
            model_name='infouser',
            name='fasebook',
            field=models.URLField(default=1, verbose_name='Фейсбук'),
            preserve_default=False,
        ),
    ]
