# Generated by Django 5.2.2 on 2025-07-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_infouser_instogram_infouser_fasebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='fasebook',
        ),
        migrations.AddField(
            model_name='infouser',
            name='github',
            field=models.URLField(default=1, verbose_name='Гитхаб'),
            preserve_default=False,
        ),
    ]
