# Generated by Django 5.2.2 on 2025-07-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_infouser_fasebook_infouser_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='Experience',
            field=models.IntegerField(default=1, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
    ]
