# Generated by Django 5.2.2 on 2025-07-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_infouser_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия услуги')),
                ('description', models.TextField(verbose_name='Описания услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Информация о пользователье', 'verbose_name_plural': 'Информация о пользователях'},
        ),
        migrations.AddField(
            model_name='infouser',
            name='emeil',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
