# Generated by Django 5.2.2 on 2025-07-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_services_alter_infouser_options_infouser_emeil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='Years_Experience',
        ),
    ]
