# Generated by Django 5.2.2 on 2025-07-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_infouser_years_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infouser',
            old_name='emeil',
            new_name='email',
        ),
    ]
