# Generated by Django 5.2.2 on 2025-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_emeil_infouser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='Начало опыта')),
                ('last_year', models.IntegerField(verbose_name='Конец опыта')),
                ('work', models.CharField(max_length=255, verbose_name='Должность')),
                ('lokation', models.CharField(max_length=255, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Год опыта',
                'verbose_name_plural': 'Годы опыта',
            },
        ),
    ]
