# Generated by Django 5.2.2 on 2025-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='Начало образования')),
                ('last_year', models.IntegerField(verbose_name='Конец образования')),
                ('lesson', models.CharField(max_length=255, verbose_name='Образования')),
                ('lokation', models.CharField(max_length=255, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Год образования',
                'verbose_name_plural': 'Годы образования',
            },
        ),
    ]
