# Generated by Django 5.2.2 on 2025-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Figma', models.IntegerField(verbose_name='Figma')),
                ('Sketch', models.IntegerField(verbose_name='Sketch')),
                ('XD', models.IntegerField(verbose_name='XD')),
                ('WordPess', models.IntegerField(verbose_name='WordPess')),
                ('React', models.IntegerField(verbose_name='React')),
                ('JavaScript', models.IntegerField(verbose_name='JavaScript')),
            ],
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='surname',
        ),
    ]
