# Generated by Django 5.2.2 on 2025-07-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_skills_remove_infouser_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Скил', 'verbose_name_plural': 'Скилы'},
        ),
    ]
