# Generated by Django 5.2.2 on 2025-07-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_skills_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='surname',
            field=models.CharField(default=1, max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
