# Generated by Django 5.2.2 on 2025-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_infouser_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='Figma',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='JavaScript',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='React',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='Sketch',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='WordPess',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='XD',
        ),
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(default=1, upload_to='infouser/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills',
            field=models.CharField(default=1, max_length=255, verbose_name='Названия скила'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_2',
            field=models.IntegerField(default=1, verbose_name='Скил'),
            preserve_default=False,
        ),
    ]
