# Generated by Django 5.2.2 on 2025-07-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_skills_figma_remove_skills_javascript_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skills_2',
            new_name='skils_2',
        ),
    ]
