# Generated by Django 5.2.2 on 2025-07-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_skills_skills_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='image',
        ),
    ]
