# Generated by Django 5.2.2 on 2025-07-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_skills_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='names',
        ),
    ]
