# Generated by Django 5.2.2 on 2025-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_name_skills_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(default=1, upload_to='infouser/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
